### PR TITLE
#94 Make adjustments to the header by dividing it into two sections: …

### PR DESCRIPTION
**Pull request by uzair-ahmed-01**
#94 Make adjustments to the header by dividing it into two sections: the logo and the navigation bar. Additionally, add a Contributors link to the navbar. The website ought to additionally include a more attractive logo, heading, and anchor links.

**Desktop Site**
Desktop

**Mobile**
Mobile

### CODE REVIEW

**Comment by Git21221** [comment]
@uzair-ahmed-01 please fix conflicts

**Comment by uzair-ahmed-01** [comment]
> @uzair-ahmed-01 please fix conflicts

I wasn't sure what I needed to fix. I want to get remove of this " master & ====== & >>>>>>> master"

**Comment by uzair-ahmed-01** [comment]
i see there is tow merge req so what should i do? @Git21221

**Comment by Git21221** [comment]
@uzair-ahmed-01 if you are stuck then try to get help from discord or youtube else you can remove your changes, pull latest changes and then work on it. always remember to update branch before pushing

**Comment by uzair-ahmed-01** [comment]
> @uzair-ahmed-01 if you are stuck then try to get help from discord or youtube else you can remove your changes, pull latest changes and then work on it. always remember to update branch before pushing

I understand. I'll fix it after lunch and then submit a pull request again. 👍@Git21221

**Pull request closed without merging**
