### PR TITLE
Qrcode for OpenAI

### PR DESCRIPTION
**Pull request by Priya16042003**

### CODE REVIEW

**Comment by Priya16042003** [comment]
Qrcode genrator

**Comment by Priya16042003** [comment]
qrcode for openai

**Comment by Git21221** [comment]
@Priya16042003 add this in Frontpage

**Comment by Priya16042003** [comment]
@Git21221 done changes in frontend

**Comment by Git21221** [comment]
@Priya16042003 can you show some video recording of this?

**Comment by Priya16042003** [comment]
@Git21221  

https://github.com/user-attachments/assets/a84a2f63-7961-4426-933c-252a8e75d018

**Comment by Priya16042003** [comment]
@Git21221 added telegram bot, pls merge it

**Comment by Git21221** [comment]
@Priya16042003 ok I can merge only qrcode for openAI only, as it's js projects so I can't merge telegram bot. please change delete the telegram bot files

**Comment by Priya16042003** [comment]
@Git21221 ok done the changes

**Pull request merged**
