### PR TITLE
Added Tmdb Movie Api App

### PR DESCRIPTION
**Pull request by rudra016**
pls add the hacktoberfest & hacktoberfest-accepted label

### CODE REVIEW

**Comment by Git21221** [comment]
@rudra016 can you please add required screenshots? so that it would be easier to me to see changes

**Comment by rudra016** [comment]
No i haven't made any changes, this is my personal project i would like to add @Git21221

**Comment by rudra016** [comment]
image

**Comment by Git21221** [comment]
@rudra016 now link this project in our main page where user can click and see your project

**Comment by rudra016** [comment]
done @Git21221 :)

**Pull request closed without merging**
