### PR TITLE
nav ui @vinodjangid07

### PR DESCRIPTION
**Pull request by vinodjangid07**
added svg icons in desktop navbar, some proper padding, margin and simple current page active state in navbar.

### CODE REVIEW

**Comment by Git21221** [comment]
@vinodjangid07 How is it looking now? can you share some of ss of the page?

**Comment by vinodjangid07** [comment]
@Git21221 
Here are the changes, simple but required
Screenshot (193)
Screenshot (192)

**Comment by vinodjangid07** [comment]
Preview :- https://deploy-preview-311--js-beginner-projects.netlify.app/

**Comment by Git21221** [comment]
@vinodjangid07 can you make all the projects visible in the web page? Cause all projects are not in the page..

**Comment by vinodjangid07** [comment]
@Git21221 Okay, i'll do that.

**Pull request closed without merging**
