### PR TITLE
Changes made to Homepage

### PR DESCRIPTION
**Pull request by krishpatel023**
I made the change to the home page and now its better looking.

Solving Issue #11 

Sample Image
image

### CODE REVIEW

**Comment by Git21221** [comment]
Please fix conflicts @krishpatel023

**Comment by krishpatel023** [comment]
Merge this first because there is no way I can keep fixing the conflicts as its the Homepage and people are adding their own app one by one. So please add this first and then let them add later. @Git21221

**Comment by Git21221** [comment]
@krishpatel023 ok I will stop merging from now....I will merge tomorrow or after your pr.

**Comment by Git21221** [comment]
Don't forget to update branch and locally use git pull <your repo link> before push

**Comment by krishpatel023** [comment]
Sure I will make the required changes

**Review by Git21221 — COMMENTED** [review]
ok

**Comment by krishpatel023** [comment]
@Git21221  Now its done. Please add this first. I also have some suggestion regarding the projects. How can I reach you directly?

**Comment by Git21221** [comment]
@krishpatel023 linkedin

**Pull request merged**
